-- =====================================================
-- Migration: Convert VARCHAR → NVARCHAR for Vietnamese encoding
-- Database: Microsoft SQL Server
-- Run this ONCE before deploying the application
-- =====================================================

-- 1. Products
ALTER TABLE products ALTER COLUMN tenSanPham NVARCHAR(255) NOT NULL;
ALTER TABLE products ALTER COLUMN chatLieu NVARCHAR(255) NULL;
ALTER TABLE products ALTER COLUMN xuatXu NVARCHAR(255) NULL;
ALTER TABLE products ALTER COLUMN mucDichSuDung NVARCHAR(255) NULL;
ALTER TABLE products ALTER COLUMN thuongHieu NVARCHAR(255) NULL;
ALTER TABLE products ALTER COLUMN kinhLoai NVARCHAR(255) NULL;
ALTER TABLE products ALTER COLUMN hinhDang NVARCHAR(255) NULL;

-- 2. Users
ALTER TABLE users ALTER COLUMN hoTen NVARCHAR(100) NOT NULL;
ALTER TABLE users ALTER COLUMN nickname NVARCHAR(100) NULL;

-- 3. Orders
ALTER TABLE orders ALTER COLUMN snapTenNguoiNhan NVARCHAR(100) NOT NULL;
ALTER TABLE orders ALTER COLUMN snapDiaChi NVARCHAR(500) NOT NULL;
ALTER TABLE orders ALTER COLUMN ghiChu NVARCHAR(500) NULL;

-- 4. Categories
ALTER TABLE categories ALTER COLUMN tenDanhMuc NVARCHAR(255) NOT NULL;
ALTER TABLE categories ALTER COLUMN moTa NVARCHAR(255) NULL;

-- 5. Addresses
ALTER TABLE addresses ALTER COLUMN tenNguoiNhan NVARCHAR(100) NOT NULL;
ALTER TABLE addresses ALTER COLUMN tinhThanh NVARCHAR(100) NOT NULL;
ALTER TABLE addresses ALTER COLUMN quanHuyen NVARCHAR(100) NOT NULL;
ALTER TABLE addresses ALTER COLUMN phuongXa NVARCHAR(100) NOT NULL;
ALTER TABLE addresses ALTER COLUMN diaChiCuThe NVARCHAR(200) NOT NULL;

-- 6. Reviews
ALTER TABLE reviews ALTER COLUMN binhLuan NVARCHAR(1000) NULL;

-- 7. Posts
ALTER TABLE posts ALTER COLUMN tieuDe NVARCHAR(300) NOT NULL;
ALTER TABLE posts ALTER COLUMN metaDescription NVARCHAR(500) NULL;
ALTER TABLE posts ALTER COLUMN tomTat NVARCHAR(500) NULL;

-- 8. PostCategories
ALTER TABLE post_categories ALTER COLUMN tenDanhMuc NVARCHAR(200) NOT NULL;
ALTER TABLE post_categories ALTER COLUMN moTa NVARCHAR(500) NULL;

-- 9. Promotions
ALTER TABLE promotions ALTER COLUMN tenChuongTrinh NVARCHAR(200) NOT NULL;

-- 10. OrderItems
ALTER TABLE order_items ALTER COLUMN tenSanPham NVARCHAR(200) NOT NULL;
ALTER TABLE order_items ALTER COLUMN tenBienThe NVARCHAR(150) NULL;

-- 11. OrderNotes
ALTER TABLE order_notes ALTER COLUMN noiDung NVARCHAR(1000) NOT NULL;
ALTER TABLE order_notes ALTER COLUMN tag NVARCHAR(50) NULL;

-- 12. OrderStatusLogs
ALTER TABLE order_status_logs ALTER COLUMN ghiChu NVARCHAR(500) NULL;

-- 13. ProductVariants
ALTER TABLE product_variants ALTER COLUMN tenBienThe NVARCHAR(255) NOT NULL;

-- 14. Roles
ALTER TABLE roles ALTER COLUMN moTa NVARCHAR(200) NULL;

-- 15. Permissions
ALTER TABLE permissions ALTER COLUMN moTa NVARCHAR(200) NULL;

-- 16. Notifications
ALTER TABLE notifications ALTER COLUMN linkLabel NVARCHAR(255) NULL;

-- 17. Banners
ALTER TABLE banners ALTER COLUMN title NVARCHAR(200) NOT NULL;
ALTER TABLE banners ALTER COLUMN description NVARCHAR(500) NULL;

-- 18. StoreInfo
ALTER TABLE store_info ALTER COLUMN tenCuaHang NVARCHAR(200) NOT NULL;
ALTER TABLE store_info ALTER COLUMN soNha NVARCHAR(100) NULL;
ALTER TABLE store_info ALTER COLUMN duong NVARCHAR(200) NULL;
ALTER TABLE store_info ALTER COLUMN phuongXa NVARCHAR(100) NULL;
ALTER TABLE store_info ALTER COLUMN quanHuyen NVARCHAR(100) NULL;
ALTER TABLE store_info ALTER COLUMN tinhThanh NVARCHAR(100) NULL;

-- 19. CustomerTags
ALTER TABLE customer_tags ALTER COLUMN tag NVARCHAR(50) NOT NULL;

-- 20. FooterLinks
ALTER TABLE footer_links ALTER COLUMN title NVARCHAR(200) NOT NULL;

-- 21. LoyaltyTransactions
ALTER TABLE loyalty_transactions ALTER COLUMN note NVARCHAR(500) NULL;

-- 22. RefundRequests
ALTER TABLE refund_requests ALTER COLUMN lydo NVARCHAR(2000) NOT NULL;
ALTER TABLE refund_requests ALTER COLUMN ghiChuXuLy NVARCHAR(255) NULL;
ALTER TABLE refund_requests ALTER COLUMN tenNganHang NVARCHAR(255) NULL;
ALTER TABLE refund_requests ALTER COLUMN chuTaiKhoan NVARCHAR(255) NULL;

-- 23. PriceHistory
ALTER TABLE price_history ALTER COLUMN variantName NVARCHAR(255) NULL;
ALTER TABLE price_history ALTER COLUMN productName NVARCHAR(255) NULL;
ALTER TABLE price_history ALTER COLUMN nguon NVARCHAR(255) NULL;

-- 24. UserSettings
ALTER TABLE user_settings ALTER COLUMN settingValue NVARCHAR(500) NULL;
