spring.application.name=DuaStore

spring.profiles.active=local

# === SQL Server ===
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DuaStore;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# === JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# === Encoding ===
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true
spring.web.resources.charset=UTF-8

# === Thymeleaf ===
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# === Upload ===
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.web.resources.static-locations=classpath:/static/,file:uploads/

# === Google Maps ===
google.maps.api.key=AIzaSyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY

# === Store Location ===
store.latitude=21.028511
store.longitude=105.854170


# === Google OAuth2 (Client ID / Secret) ===
# Di den https://console.cloud.google.com/ \u00e2\u0086\u0092 APIs & Services \u00e2\u0086\u0092 Credentials \u00e2\u0086\u0092 Tao OAuth 2.0 Client ID
spring.security.oauth2.client.registration.google.client-id=251555437081-2etmqn7kqqflt16edt0stikju6ef81id.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# === GMAIL SMTP ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenhuydung1506@gmail.com
spring.mail.password=vzof jccd yaln qwys
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

# === Payment ===
payment.bank.code=TCB
payment.bank.account.number=19076525108012
payment.bank.account.name=Nguyen Huy Dung

# === Server ===
server.tomcat.connection-timeout=20000
